In [9]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rakeshkapilavai/extrovert-vs-introvert-behavior-data")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Harsh Yadav\.cache\kagglehub\datasets\rakeshkapilavai\extrovert-vs-introvert-behavior-data\versions\2

In [17]:
import pandas as pd

file_path = r"C:\Users\Harsh Yadav\.cache\kagglehub\datasets\rakeshkapilavai\extrovert-vs-introvert-behavior-data\versions\2\personality_datasert.csv"

df = pd.read_csv(file_path)

# Display first 5 rows
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [24]:
# Displaying all the information from the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   object
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   object
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   object
dtypes: float64(5), object(3)
memory usage: 181.4+ KB

In [32]:
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [29]:
print(df.duplicated().sum())

402

In [34]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [35]:
print(df[df.duplicated()])

      Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
47                10.0        Yes                      1.0            2.0
217                5.0        Yes                      2.0            0.0
246                9.0        Yes                      0.0            1.0
248                9.0        Yes                      0.0            2.0
254                7.0        Yes                      0.0            0.0
...                ...        ...                      ...            ...
2884              11.0        Yes                      0.0            2.0
2890               8.0        Yes                      2.0            0.0
2891               6.0        Yes                      3.0            1.0
2892               9.0        Yes                      2.0            0.0
2895               3.0         No                      7.0            6.0

     Drained_after_socializing  Friends_circle_size  Post_frequency  \
47                         Yes                  2.0             0.0
217                        Yes                  2.0             0.0
246                        Yes                  2.0             1.0
248                        Yes                  3.0             2.0
254                        Yes                  3.0             2.0
...                        ...                  ...             ...
2884                       Yes                  3.0             1.0
2890                       Yes                  1.0             2.0
2891                       Yes                  5.0             1.0
2892                       Yes                  1.0             2.0
2895                        No                  6.0             6.0

     Personality
47     Introvert
217    Introvert
246    Introvert
248    Introvert
254    Introvert
...          ...
2884   Introvert
2890   Introvert
2891   Introvert
2892   Introvert
2895   Extrovert

[402 rows x 8 columns]

In [36]:
print(df[df.duplicated(keep=False)])

      Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
2                  9.0        Yes                      1.0            2.0
3                  0.0         No                      6.0            7.0
13                 3.0         No                      6.0            4.0
20                10.0        Yes                      3.0            1.0
23                 9.0        Yes                      2.0            2.0
...                ...        ...                      ...            ...
2884              11.0        Yes                      0.0            2.0
2890               8.0        Yes                      2.0            0.0
2891               6.0        Yes                      3.0            1.0
2892               9.0        Yes                      2.0            0.0
2895               3.0         No                      7.0            6.0

     Drained_after_socializing  Friends_circle_size  Post_frequency  \
2                          Yes                  5.0             2.0
3                           No                 14.0             8.0
13                          No                 10.0             7.0
20                         Yes                  2.0             1.0
23                         Yes                  1.0             0.0
...                        ...                  ...             ...
2884                       Yes                  3.0             1.0
2890                       Yes                  1.0             2.0
2891                       Yes                  5.0             1.0
2892                       Yes                  1.0             2.0
2895                        No                  6.0             6.0

     Personality
2      Introvert
3      Extrovert
13     Extrovert
20     Introvert
23     Introvert
...          ...
2884   Introvert
2890   Introvert
2891   Introvert
2892   Introvert
2895   Extrovert

[731 rows x 8 columns]

In [37]:
df.drop_duplicates()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.000000,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.000000,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.000000,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.000000,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.000000,Extrovert
...,...,...,...,...,...,...,...,...
2894,0.0,No,9.0,3.0,No,12.0,3.564727,Extrovert
2896,3.0,No,8.0,3.0,No,14.0,9.000000,Extrovert
2897,4.0,Yes,1.0,1.0,Yes,4.0,0.000000,Introvert
2898,11.0,Yes,1.0,3.0,Yes,2.0,0.000000,Introvert
2899,3.0,No,6.0,6.0,No,6.0,9.000000,Extrovert

In [39]:
df['Personality'].value_counts()

Personality
Extrovert    1491
Introvert    1409
Name: count, dtype: int64

In [46]:
percentages = df['Personality'].value_counts(normalize=True)*100
rounded = percentages.round()
print(rounded)

Personality
Extrovert    51.0
Introvert    49.0
Name: proportion, dtype: float64

In [47]:
print(df.groupby('Personality').mean(numeric_only=True))

             Time_spent_Alone  Social_event_attendance  Going_outside  \
Personality
Extrovert            2.122869                 5.977850       4.596244
Introvert            7.027444                 1.831621       1.310859

             Friends_circle_size  Post_frequency
Personality
Extrovert               9.095744        5.592647
Introvert               3.277465        1.418787

In [58]:
df['is_extrovert'] = (df['Personality'] == 'Extrovert').astype(int)
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality,is_extrovert
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert,1
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert,0
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert,0
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert,1
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert,1
...,...,...,...,...,...,...,...,...,...
2895,3.0,No,7.0,6.0,No,6.0,6.0,Extrovert,1
2896,3.0,No,8.0,3.0,No,14.0,9.0,Extrovert,1
2897,4.0,Yes,1.0,1.0,Yes,4.0,0.0,Introvert,0
2898,11.0,Yes,1.0,3.0,Yes,2.0,0.0,Introvert,0
2899,3.0,No,6.0,6.0,No,6.0,9.0,Extrovert,1

In [10]:
# Using Normalization to range numbers btw 0 to 1 
import numpy as np
import pandas as pd

file_path = r"C:\Users\Harsh Yadav\.cache\kagglehub\datasets\rakeshkapilavai\extrovert-vs-introvert-behavior-data\versions\2\personality_datasert.csv"
df = pd.read_csv(file_path)

for col in df.select_dtypes(include=['float64','int64']).columns:
    col_min = df[col].min()
    col_max = df[col].max()

    # Normalization = x-min/max-min
    df[col] = (df[col] - col_min) / (col_max - col_min)
print(df.head())

NameError: name 'file_path' is not defined